development: &development
  adapter: postgresql
  database: solution3_development
  username: root
  password: root 
  pool: 5
  timeout: 5000

test:
  <<: *development
  database: solution3_test

production: &production
  adapter: postgresql
  database: solution3_production
  pool: 5
  timeout: 5000

staging:
  <<: *production
  database: solution3_staging

integration:
  <<: *production
  database: solution3_integration

# Matching environments specified in this file will override the above.
<%= IO.read('config/database.local.yml') if File.exists?('config/database.local.yml') %>
